apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: kubernetes-container-logs
        enabled: true
        paths:
          - /var/log/*.log
        parsers:
          - ndjson:
              keys_under_root: true
              add_error_key: true

    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
