apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        paths:
          - /var/log/*.log
        multiline:
          pattern: '^\d{4}-\d{2}-\d{2}'
          negate: true
          match: after

    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
