apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/containers/*.log
        symlinks: true
        json.keys_under_root: true
        json.add_error_key: true
        json.message_key: log

    processors:
      - add_kubernetes_metadata:
          in_cluster: true

    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST:http://elasticsearch:9200}"]
